apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki_client-app
  labels:
    app: wiki_client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wiki_client
  template:
    metadata:
      labels:
        app: wiki_client
    spec:
      containers:
        - image: postgres:alpine3.16
          name: wiki_client
          ports:
            - containerPort: 8000
              name: gunicorn